### ISSUE TITLE
Dockerized sample app doesn't run through GUI

### ISSUE THREAD

**Issue by blthayer** [GRIDAPPSD/gridappsd-sample-app#6]
@poorvasharma @craig8 
**Setup**
gridappsd-docker: `develop 83eb76f0af430454c4fe6c528c1b8fa10553cc52`
gridappsd-sample-app `dockerize c341c82c356fe9d68490392d2c06d9572018d07a`

I followed the directions in the gridappsd-sample-app README to get the platform started with the sample app. When I attempted to run a simulation through the GUI, I got the following error:

```
{
    "source": "ProcessNewSimulationRequest",
    "processId": "1705413762",
    "timestamp": 1537226070507,
    "logMessage": "Cannot start application sample_app. Application not available",
    "logLevel": "ERROR",
    "processStatus": "ERROR",
    "storeToDb": true
}
```
Other times, I got a very similar error, but oddly the message didn't have "sample_app" in it, and instead read: "Cannot start application . Application not available"

**Comment by craigpnnl** [comment]
Thanks for the report.  I believe this is because I haven't put the code out that does all the registration etc.  I will have that out today and will work with you to get this accomplished.

**Comment by blthayer** [comment]
@craig8 - What's the status on this? I'd like to take a shot at it myself before we meet on Friday.
